[theme]
primaryColor = "#6366f1"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f1f5f9"
font = "sans serif"

[server]
maxUploadSize = 5
enableXsrfProtection = true
enableCORS = false
headless = true
port = 8501

[browser]
gatherUsageStats = false
